//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputosPJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Afiliados
    {
        public int Id { get; set; }
        public string ApellidoNombre { get; set; }
        public string Apellido { get; set; }
        public string Nombre { get; set; }
        public Nullable<long> Matricula { get; set; }
        public string Domicilio { get; set; }
        public string Seccion { get; set; }
        public Nullable<int> SeccionCod { get; set; }
        public string Circuito { get; set; }
        public string CircuitoCod { get; set; }
        public string FechaNacimiento { get; set; }
        public Nullable<int> Clase { get; set; }
        public string Profesion { get; set; }
        public string FechaDomicilio { get; set; }
        public string Partido { get; set; }
    }
}
