//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputosPJ.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ComputosPJEntities : DbContext
    {
        public ComputosPJEntities()
            : base("name=ComputosPJEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<Accion> Accion { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<MenuAspNetRoles> MenuAspNetRoles { get; set; }
        public virtual DbSet<MenuAspNetRolesAccion> MenuAspNetRolesAccion { get; set; }
        public virtual DbSet<Circuito> Circuito { get; set; }
        public virtual DbSet<Eleccion> Eleccion { get; set; }
        public virtual DbSet<EnlaceEleccionEscuela> EnlaceEleccionEscuela { get; set; }
        public virtual DbSet<EnlaceEleccionTipoCategoria> EnlaceEleccionTipoCategoria { get; set; }
        public virtual DbSet<EnlaceEleccionTipoCategoriaLista> EnlaceEleccionTipoCategoriaLista { get; set; }
        public virtual DbSet<JuntaDepartamental> JuntaDepartamental { get; set; }
        public virtual DbSet<Lista> Lista { get; set; }
        public virtual DbSet<Mesa> Mesa { get; set; }
        public virtual DbSet<Municipio> Municipio { get; set; }
        public virtual DbSet<RecuentoVoto> RecuentoVoto { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TipoCategoria> TipoCategoria { get; set; }
        public virtual DbSet<TipoPartidoPolitico> TipoPartidoPolitico { get; set; }
        public virtual DbSet<Escuela> Escuela { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
    
        public virtual ObjectResult<GetPermisosPorNombreDeUsuario_Result> GetPermisosPorNombreDeUsuario(string userName)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPermisosPorNombreDeUsuario_Result>("GetPermisosPorNombreDeUsuario", userNameParameter);
        }
    }
}
