//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputosPJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Padron
    {
        public int ID { get; set; }
        public string Apellido { get; set; }
        public string Nombre { get; set; }
        public string TipoMatricula { get; set; }
        public long Matricula { get; set; }
        public string Domicilio { get; set; }
        public string NumeroCircuito { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<int> Clase { get; set; }
        public string Profesion { get; set; }
        public Nullable<System.DateTime> FechaDomicilio { get; set; }
        public string Sexo { get; set; }
        public Nullable<bool> EsAfiliado { get; set; }
        public string AfiliadoCircuito { get; set; }
        public Nullable<int> AvalMunicipioID { get; set; }
        public string AvalLista { get; set; }
        public Nullable<System.DateTime> AvalFechaAlta { get; set; }
        public Nullable<int> AvalUsuarioAppIDAlta { get; set; }
        public string Afiliado { get; set; }
    }
}
